### Create User with Profile Image
POST http://localhost:3000/users/create
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="email"

ahmadogo@gmail.com
--MyBoundary
Content-Disposition: form-data; name="password"

StrongPassword123
--MyBoundary
Content-Disposition: form-data; name="firstName"

Ahmad
--MyBoundary
Content-Disposition: form-data; name="lastName"

Dogo
--MyBoundary
Content-Disposition: form-data; name="bio"

StrellerMinds to the world !
--MyBoundary
Content-Disposition: form-data; name="file"; filename="profile.jpg"
Content-Type: image/jpeg

< ./profile.jpg
--MyBoundary--
