import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, Index } from "typeorm"

@Entity("content_labels")
@Index(["content_type", "content_id"])
@Index(["language_code"])
export class ContentLabel {
  @PrimaryGeneratedColumn("uuid")
  id: string

  @Column({ name: "content_type" })
  contentType: string

  @Column({ name: "content_id" })
  contentId: string

  @Column({ name: "label_type" })
  labelType: "alt" | "aria-label" | "title" | "description" | "caption" | "summary"

  @Column({ name: "label_text", type: "text" })
  labelText: string

  @Column({ name: "language_code", default: "en" })
  languageCode: string

  @Column({ name: "context", nullable: true })
  context?: string

  @Column({ name: "is_auto_generated", default: false })
  isAutoGenerated: boolean

  @Column({ name: "confidence_score", type: "decimal", precision: 3, scale: 2, nullable: true })
  confidenceScore?: number

  @Column({ name: "source", nullable: true })
  source?: "manual" | "ai" | "ocr" | "speech-to-text" | "imported"

  @Column({ name: "is_approved", default: false })
  isApproved: boolean

  @Column({ name: "approved_by", nullable: true })
  approvedBy?: string

  @Column({ name: "approved_at", nullable: true })
  approvedAt?: Date

  @CreateDateColumn({ name: "created_at" })
  createdAt: Date

  @UpdateDateColumn({ name: "updated_at" })
  updatedAt: Date
}
